### ISSUE TITLE
authenticator window size issue

### ISSUE THREAD

**Issue by 32xxl** [Sneezry/authenticator#13]
https://youtu.be/Oeaw91zmw0A

Google authenticator window size issue 

When click to the Google authenticator button, it open in normal size and then resize to little window. This is problem, because where is no possibility to use Google authenticator in this small window. 

How ti fix?

**Comment by Sneezry** [comment]
Ooooops...

In fact, this is because I just pushed a new commit to solve issue #12... We have made JS detect zoom setting, and try to make the popup page look same under different zooms...

Depending on your video, I guess the code fails to detect zoom setting correctly, and it thinks you are under large zoom, so it scales the popup page to a small one.

Could you tell me your zoom settings and is your display a retina one?

**Comment by 32xxl** [comment]
I use 1280 x 1024 pixels on desktop Win XP SP3

**Comment by 32xxl** [comment]
Also, when for test change resolution to 1024 x 768 pixels - I have same story

**Comment by 32xxl** [comment]
And I don't use any zoom settings, all settings by default.

**Comment by Sneezry** [comment]
Could you please right click on the extension icon and click Inspect Popup, then click Console, and tell me the number you can see? Thanks.

**Comment by 32xxl** [comment]
320

**Comment by Sneezry** [comment]
I have rolled back the code to disable this feature(in fact a bug) in version 4.12, and please update your extension in 30min to 1hour to fix it.

**Comment by Sneezry** [comment]
Thanks for your feedback :-)

**Comment by 32xxl** [comment]
320 in 1024 x 768  px
400 in 1280 x 1024 px 

ok, thank you)

**Comment by Sneezry** [comment]
The newest version is available in web store now, please manual update the extension by checking developer mode and clicking update extensions now button in extension settings page.
