### ISSUE TITLE
Google Authenticator 

### ISSUE THREAD

**Issue by serhz69** [Sneezry/authenticator#238]
Перестал показывать коды.
Посмотрел в обновления сегодня была обнова.
Разрабы исправляйте,время- деньги. Иначе зачем он нам нужен???
![28-01-2018 214338](https://user-images.githubusercontent.com/35898400/35485142-7e2a2070-0474-11e8-8983-4ed52471f82f.png)

**Comment by Sneezry** [comment]
Authenticator for Chrome extension 4.19 has an issue to show codes, but your data is safe. The issue is caused by undefined namespace which is used in Firefox:

https://github.com/Sneezry/authenticator/blob/ed23dd24718c4712823a13ee419036591b524b4f/javascript/popup.js#L60

4.20 is released, and your extension should be upgraded in one hour.

**Comment by serhz69** [comment]
Спасибо,все заработало хорошо.
