### ISSUE TITLE
AUTHENTICATOR NOT WORKING

### ISSUE THREAD

**Issue by TenDot4** [Sneezry/authenticator#239]
After the latest update in Jan 28, 2018, authenticator stopped working. Now, I can't access online banking or other important accounts because of this issue. The authenticator screen stays blank. Can't access its settings or even create a new entry. Please help!

**Comment by mymindstorm** [comment]
Duplicate of #223

Your codes are safe, fix coming soon

**Comment by hoangquan1** [comment]
không hiển thị mã trong google authentitator

**Comment by Sneezry** [comment]
Authenticator for Chrome extension 4.19 has an issue to show codes, but your data is safe. The issue is caused by undefined namespace which is used in Firefox:

https://github.com/Sneezry/authenticator/blob/ed23dd24718c4712823a13ee419036591b524b4f/javascript/popup.js#L60

4.20 is released, and your extension should be upgraded in one hour.

**Comment by TenDot4** [comment]
Thanks. Issue is now fixed with the 4.20 update. Glad to know that everything is working as it used to.

**Comment by Sneezry** [comment]
@TenDot4 please take some seconds to make a backup, this time we are lucky
