### ISSUE TITLE
fix coming soon? how soon? tyme is money baby!

### ISSUE THREAD

**Issue by thetree3** [Sneezry/authenticator#240]
soooooon?

**Comment by mymindstorm** [comment]
12-24 hr eta

**Comment by thetree3** [comment]
24 hours?????? u are serious, i cant access my own account for 24hours, u must be joking

**Comment by mymindstorm** [comment]
Spamming is 100% not going to help anything

**Comment by thetree3** [comment]
definitely not trying to "spam" anyone... but i cant access a single cent of my own money, i hope u understand the seriousness of this, im trying to keep a light attitude rather than totally freaking out, i dont appreciate being associated with "spamming"

**Comment by mymindstorm** [comment]
You shouldn't rely solely on this extension to access your important accounts. There are account recovery methods to get your account back if you lose your codes. My inbox is getting more email by the minute (~50+ emails total currently) and I've answered the question you asked at least three times prior to this conversation. Sorry if I'm a bit irate but this issue is driving me crazy.

**Comment by ricashrq88** [comment]
yo tambien tengo el mismo problema no me genera ningun codigo ,,, se han acabdo mis codigo .. ????

**Comment by janfiedler** [comment]
@thetree3 If you have backup  I hope you have. You can import your secret key to another aplication and use it for access your money.

**Comment by galycar** [comment]
@janfielder I have my secret key,  can you tell me please, what other aplication is useful?

**Comment by galycar** [comment]
@janfiedler  I have my secret key, can you tell me please, what other aplication is useful?

**Comment by janfiedler** [comment]
@galycar  When you use any other app, you can put your secret key manually or use qr code. But in this situation you fill your secret key manually and thats all. For example you can use mobile app Google Authenticator

**Comment by Sneezry** [comment]
Authenticator for Chrome extension 4.19 has an issue to show codes, but your data is safe. The issue is caused by undefined namespace which is used in Firefox:

https://github.com/Sneezry/authenticator/blob/ed23dd24718c4712823a13ee419036591b524b4f/javascript/popup.js#L60

4.20 is released, and your extension should be upgraded in one hour.

**Comment by galycar** [comment]
@janfiedler thanks!
