### ISSUE TITLE
AUTHENTICATOR NOT WORKING

### ISSUE THREAD

**Issue by Raffaele123** [Sneezry/authenticator#242]
l'autenticatore ha smesso di operare. Ora, non posso accedere a servizi bancari online o altri account importanti a causa di questo problema. mi aiutate per favore.

**Comment by Sneezry** [comment]
Authenticator for Chrome extension 4.19 has an issue to show codes, but your data is safe. The issue is caused by undefined namespace which is used in Firefox:

https://github.com/Sneezry/authenticator/blob/ed23dd24718c4712823a13ee419036591b524b4f/javascript/popup.js#L60

4.20 is released, and your extension should be upgraded in one hour.
