### ISSUE TITLE
the authy is NONWORKING...

### ISSUE THREAD

**Issue by worstapp** [Sneezry/authenticator#243]
CRASH and NONWORKING AUTHY.
911................................................911.....................

**Comment by mymindstorm** [comment]
Duplicate of #223

Your codes are safe, fix coming soon

**Comment by Sneezry** [comment]
Authenticator for Chrome extension 4.19 has an issue to show codes, but your data is safe. The issue is caused by undefined namespace which is used in Firefox:

https://github.com/Sneezry/authenticator/blob/ed23dd24718c4712823a13ee419036591b524b4f/javascript/popup.js#L60

4.20 is released, and your extension should be upgraded in one hour.
