### ISSUE TITLE
the code in the authenticator extension was missing

### ISSUE THREAD

**Issue by avlion82** [Sneezry/authenticator#246]
I also have this problem, all the codes are gone. The gear does not respond. Removed anew I did not help.

**Comment by janfiedler** [comment]
Hi, I have same problem. Reinstall dosent help.

**Comment by Sneezry** [comment]
Authenticator for Chrome extension 4.19 has an issue to show codes, but your data is safe. The issue is caused by undefined namespace which is used in Firefox:

https://github.com/Sneezry/authenticator/blob/ed23dd24718c4712823a13ee419036591b524b4f/javascript/popup.js#L60

4.20 is released, and your extension should be upgraded in one hour.
