### ISSUE TITLE
My Authenticator Can't open

### ISSUE THREAD

**Issue by dhongfel17** [Sneezry/authenticator#249]
Please resolve my authenticator not working I have to open banking account-.
how to resolve this problem. Please Resolve the problem
![authenticator not working](https://user-images.githubusercontent.com/35900307/35486026-16596fa0-0479-11e8-8a5d-a8b20ac48ae2.PNG)

Best Regards

**Comment by pritamabc** [comment]
i also have the same problem..kindly help me

**Comment by syspythonxaxaxa** [comment]
same here!

**Comment by Sneezry** [comment]
Authenticator for Chrome extension 4.19 has an issue to show codes, but your data is safe. The issue is caused by undefined namespace which is used in Firefox:

https://github.com/Sneezry/authenticator/blob/ed23dd24718c4712823a13ee419036591b524b4f/javascript/popup.js#L60

4.20 is released, and your extension should be upgraded in one hour.
