### ISSUE TITLE
Release

### ISSUE THREAD

**Issue by robinkanters** [Sneezry/authenticator#34]
Could you please tag and upload a new minor release? The remeber spelling is still out there.

**Comment by Sneezry** [comment]
Hi @robinkanters , sorry for my procrastination. I thought to release a new version without typo after I fix some other bugs, however, passphrase issue hasn't reappeared for me until now. I'll release a new version shortly to fix typo issue, and passphrase issue may be fixed in a later version.

Thanks for your feedback :)
Zhe Li

**Comment by Sneezry** [comment]
4.17 is available in web store now.

**Comment by robinkanters** [comment]
Thanks! :+1:
